ú2:11:320:15:28:29.906 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
ú2:11:320:15:28:29.915 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:278) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
ú2:11:320:15:28:30.412 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - Unknown table 'schedule' in field list
ú2:11:320:15:28:30.412 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
ú2:11:320:18:47:54.732 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
ú2:11:320:18:47:54.744 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:278) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
ú2:11:320:18:47:55.052 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - Unknown table 'schedule' in field list
ú2:11:320:18:47:55.052 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:325:17:19:37.362 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:325:17:19:37.373 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:279) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:325:17:19:38.004 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:325:17:19:38.004 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:325:17:20:39.298 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:325:17:20:39.306 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:279) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:325:17:20:39.896 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:325:17:20:39.896 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:326:10:55:27.271 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:326:10:55:27.281 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:326:10:55:31.205 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:326:10:55:31.206 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:07:04.595 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:07:04.605 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:07:05.143 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:07:05.144 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:08:32.076 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:08:32.089 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:08:32.787 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:08:32.788 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:08:55.597 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:08:55.607 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:08:56.032 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:08:56.032 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:14:12.049 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:14:12.063 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:14:12.307 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:14:12.308 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:14:25.640 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:14:25.654 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:14:25.871 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'thirduser' for key 'user.login_UNIQUE'
2022:11:327:13:14:25.919 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:14:25.923 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - it is impossible to add schedule
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.ScheduleService.addSchedule(ScheduleService.java:104) ~[classes/:?]
	at by.training.beauty.service.ScheduleServiceTest.testAddschedule(ScheduleServiceTest.java:66) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.ScheduleDaoImpl.create(ScheduleDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.dao.mysql.ScheduleDaoImpl.create(ScheduleDaoImpl.java:20) ~[classes/:?]
	at by.training.beauty.service.ScheduleService.addSchedule(ScheduleService.java:93) ~[classes/:?]
	... 26 more
2022:11:327:13:14:25.931 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:14:25.931 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:14:26.011 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:14:26.147 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:14:26.147 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:14:26.191 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:14:45.910 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:14:45.921 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:16:01.331 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:16:01.331 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:16:31.521 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:16:31.532 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:17:16.252 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:17:16.253 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:19:52.764 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:19:52.770 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:19:52.959 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:19:52.959 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:19:53.115 [by.training.beauty.dao.mysql.UserDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.UserDaoImpl - Cannot delete or update a parent row: a foreign key constraint fails
2022:11:327:13:19:53.117 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - it is impossible to delete user
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.UserService.deleteUser(UserService.java:162) ~[classes/:?]
	at by.training.beauty.service.UserServiceTest.testDeleteUser(UserServiceTest.java:115) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.UserDaoImpl.delete(UserDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.service.UserService.deleteUser(UserService.java:149) ~[classes/:?]
	... 26 more
2022:11:327:13:20:23.555 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:20:23.564 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:22:26.392 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:22:26.392 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:22:26.546 [by.training.beauty.dao.mysql.UserDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.UserDaoImpl - Cannot delete or update a parent row: a foreign key constraint fails
2022:11:327:13:22:26.549 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - it is impossible to delete user
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.UserService.deleteUser(UserService.java:162) ~[classes/:?]
	at by.training.beauty.service.UserServiceTest.testDeleteUser(UserServiceTest.java:115) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.UserDaoImpl.delete(UserDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.service.UserService.deleteUser(UserService.java:149) ~[classes/:?]
	... 26 more
2022:11:327:13:25:46.109 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:25:46.118 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:25:46.340 [by.training.beauty.dao.mysql.UserDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.UserDaoImpl - Cannot delete or update a parent row: a foreign key constraint fails
2022:11:327:13:25:46.343 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - it is impossible to delete user
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.UserService.deleteUser(UserService.java:162) ~[classes/:?]
	at by.training.beauty.service.UserServiceTest.testDeleteUser(UserServiceTest.java:115) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.UserDaoImpl.delete(UserDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.service.UserService.deleteUser(UserService.java:149) ~[classes/:?]
	... 26 more
2022:11:327:13:25:46.494 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:25:46.495 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:26:01.225 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:26:01.245 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:26:01.581 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:26:01.581 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:26:01.969 [by.training.beauty.dao.mysql.UserDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.UserDaoImpl - Cannot delete or update a parent row: a foreign key constraint fails
2022:11:327:13:26:01.972 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - it is impossible to delete user
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.UserService.deleteUser(UserService.java:162) ~[classes/:?]
	at by.training.beauty.service.UserServiceTest.testDeleteUser(UserServiceTest.java:115) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.UserDaoImpl.delete(UserDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.service.UserService.deleteUser(UserService.java:149) ~[classes/:?]
	... 26 more
2022:11:327:13:29:51.042 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:29:51.055 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:31:14.456 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:31:14.463 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:31:14.723 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:31:14.724 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:31:14.955 [by.training.beauty.dao.mysql.UserDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.UserDaoImpl - Cannot delete or update a parent row: a foreign key constraint fails
2022:11:327:13:31:14.959 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - it is impossible to delete user
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.UserService.deleteUser(UserService.java:162) ~[classes/:?]
	at by.training.beauty.service.UserServiceTest.testDeleteUser(UserServiceTest.java:115) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.UserDaoImpl.delete(UserDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.service.UserService.deleteUser(UserService.java:149) ~[classes/:?]
	... 26 more
2022:11:327:13:32:21.645 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:32:21.656 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:32:26.051 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:32:26.051 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:32:26.427 [by.training.beauty.dao.mysql.UserDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.UserDaoImpl - Cannot delete or update a parent row: a foreign key constraint fails
2022:11:327:13:32:26.430 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - it is impossible to delete user
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.UserService.deleteUser(UserService.java:162) ~[classes/:?]
	at by.training.beauty.service.UserServiceTest.testDeleteUser(UserServiceTest.java:115) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.UserDaoImpl.delete(UserDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.service.UserService.deleteUser(UserService.java:149) ~[classes/:?]
	... 26 more
2022:11:327:13:33:19.520 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:33:19.540 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:33:20.091 [by.training.beauty.dao.mysql.UserDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.UserDaoImpl - Cannot delete or update a parent row: a foreign key constraint fails
2022:11:327:13:33:20.095 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - it is impossible to delete user
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.UserService.deleteUser(UserService.java:162) ~[classes/:?]
	at by.training.beauty.service.UserServiceTest.testDeleteUser(UserServiceTest.java:115) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.UserDaoImpl.delete(UserDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.service.UserService.deleteUser(UserService.java:149) ~[classes/:?]
	... 26 more
2022:11:327:13:33:20.247 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:33:20.248 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:33:39.385 [by.training.beauty.dao.mysql.AppointmentDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.AppointmentDaoImpl - Cannot add or update a child row: a foreign key constraint fails
2022:11:327:13:33:39.393 [by.training.beauty.service.AppointmentServiceTest  -----+`  t] ERROR by.training.beauty.service.AppointmentServiceTest - it is impossible to update appointment
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:212) ~[classes/:?]
	at by.training.beauty.service.AppointmentServiceTest.testUpdateAppointment(AppointmentServiceTest.java:113) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:280) ~[classes/:?]
	at by.training.beauty.dao.mysql.AppointmentDaoImpl.update(AppointmentDaoImpl.java:19) ~[classes/:?]
	at by.training.beauty.service.AppointmentService.updateAppointment(AppointmentService.java:202) ~[classes/:?]
	... 26 more
2022:11:327:13:33:39.885 [by.training.beauty.dao.mysql.ScheduleDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.ScheduleDaoImpl - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.id = 1' at line 1
2022:11:327:13:33:39.885 [by.training.beauty.service.ScheduleServiceTest  -----+`  t] ERROR by.training.beauty.service.ScheduleServiceTest - an error occurred while getting schedule
2022:11:327:13:33:40.033 [by.training.beauty.dao.mysql.UserDaoImpl  -----+`  t] ERROR by.training.beauty.dao.mysql.UserDaoImpl - Cannot delete or update a parent row: a foreign key constraint fails
2022:11:327:13:33:40.036 [by.training.beauty.service.UserServiceTest  -----+`  t] ERROR by.training.beauty.service.AdministrateServiceTest - it is impossible to delete user
by.training.beauty.service.ServiceException: by.training.beauty.dao.DaoException
	at by.training.beauty.service.UserService.deleteUser(UserService.java:162) ~[classes/:?]
	at by.training.beauty.service.UserServiceTest.testDeleteUser(UserServiceTest.java:115) ~[test-classes/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146) ~[testng-7.4.0.jar:7.4.0]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128) ~[testng-7.4.0.jar:7.4.0]
	at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:794) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestRunner.run(TestRunner.java:596) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunner.run(SuiteRunner.java:276) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53) [testng-7.4.0.jar:7.4.0]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.runSuites(TestNG.java:1063) [testng-7.4.0.jar:7.4.0]
	at org.testng.TestNG.run(TestNG.java:1031) [testng-7.4.0.jar:7.4.0]
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66) [testng-rt.jar:?]
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109) [testng-rt.jar:?]
Caused by: by.training.beauty.dao.DaoException
	at by.training.beauty.dao.mysql.UserDaoImpl.delete(UserDaoImpl.java:215) ~[classes/:?]
	at by.training.beauty.service.UserService.deleteUser(UserService.java:149) ~[classes/:?]
	... 26 more
